@echo off
REM ----------------------------------------------------------------------------
REM Maven wrapper for Windows
REM ----------------------------------------------------------------------------
REM This script was generated by the Apache Maven™ Wrapper (https://github.com/takari/maven-wrapper)

setlocal
set BASEDIR=%~dp0
set MAVEN_WRAPPER_DIR=%BASEDIR%\.mvn\wrapper
set MAVEN_WRAPPER_JAR=%MAVEN_WRAPPER_DIR%\maven-wrapper.jar
if not exist "%MAVEN_WRAPPER_JAR%" (
  echo Maven Wrapper JAR not found. To generate it, run on your machine:
  echo   mvn -N org.apache.maven.plugins:maven-wrapper:3.1.1:wrapper
  echo Or run the same command with your preferred Maven version.
  exit /b 1
)
java -jar "%MAVEN_WRAPPER_JAR%" %*
endlocal

